### ISSUE TITLE
TrashbinMigrator without FilesMigrator errors on loading Files webview

### ISSUE THREAD

**Issue by Pytal** [nextcloud/user_migration#96]
TrashbinMigrator runs export and import successfully without FilesMigrator but when loading the Files webview after importing it throws `\OCP\Files\NotFoundException`, details below

```
Technical details
Remote Address: 127.0.0.1
Request ID: nrGT0EYgBJXTsOLlwTTU
OCP\Files\NotFoundException
0
/var/www/nextcloud/lib/private/legacy/OC_Helper.php
496

Trace
#0 /var/www/nextcloud/apps/files/lib/Controller/ViewController.php(154): OC_Helper::getStorageInfo()
#1 /var/www/nextcloud/apps/files/lib/Controller/ViewController.php(204): OCA\Files\Controller\ViewController->getStorageInfo()
#2 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(225): OCA\Files\Controller\ViewController->index()
#3 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(133): OC\AppFramework\Http\Dispatcher->executeController()
#4 /var/www/nextcloud/lib/private/AppFramework/App.php(172): OC\AppFramework\Http\Dispatcher->dispatch()
#5 /var/www/nextcloud/lib/private/Route/Router.php(298): OC\AppFramework\App::main()
#6 /var/www/nextcloud/lib/base.php(1023): OC\Route\Router->match()
#7 /var/www/nextcloud/index.php(36): OC::handleRequest()
#8 {main}
```

**Comment by come-nc** [comment]
I’m failing to reproduce this, can you give exact instructions? Do I need to have something special in my trashbin?
Do I need to export/import through UI or console?

I put everything in the trash with a user and exported only trashbin, then I logged with another user and imported through UI, it worked, the files were in the trashbin and I can restore them.

**Comment by Pytal** [comment]
Reproduced on server and user_migration `stable25` branches

1) Login as admin
2) Upload some files and delete a few so they are in the trashbin
3) Run `occ user:export --types=trashbin admin <dir>`
4) Create user steve
5) Run `occ user:import --user=steve <archive_path>`
6) Login as steve and open Files webview

**Comment by come-nc** [comment]
> Reproduced on server and user_migration `stable25` branches
> 
> 1. Login as admin
> 2. Upload some files and delete a few so they are in the trashbin
> 3. Run `occ user:export --types=trashbin admin <dir>`
> 4. Create user steve
> 5. Run `occ user:import --user=steve <archive_path>`
> 6. Login as steve and open Files webview

I’m still failing to reproduce an error.

I do have an empty list in files, but I cannot find where you see an Exception.

The empty list I think comes from the fact that the user after import is seen as having already connected before, I do not have the first run wizard either. But firstrunwizard use its own setting iirc, so not sure it is the same one for default files.

**Comment by Pytal** [comment]
Probably only happens on a minimal setup with Apache2, SQLite, and APCu then 🤔

**Comment by come-nc** [comment]
Ideas:
- May be time sensitive, if caching is involved
- Maybe I did a user:info or so on the user that "fixed" the issue

@icewind1991 Could you give us some insight on user home folder creation?
When should it be created, and what would be the reason for it to trigger a filenotfound exception instead of just creating the folder?
Is it most likely related to files_trashbin folder existing or to some database content?

**Comment by come-nc** [comment]
> > * Create user steve
> > * Run `occ user:import --user=steve <archive_path>`
> > * Login as steve and open Files webview
> 
> I guess this is the problem. without logging in first, the setup routine is not triggered. This is currently by design IIRC.

Ok, but where is the setup routine, and how can we trigger it in the import code?

**Comment by szaimen** [comment]
> > > * Create user steve
> > > * Run `occ user:import --user=steve <archive_path>`
> > > * Login as steve and open Files webview
> > 
> > 
> > I guess this is the problem. without logging in first, the setup routine is not triggered. This is currently by design IIRC.
> 
> Ok, but where is the setup routine, and how can we trigger it in the import code?

No idea, sry! Cc @blizzz maybe?

**Comment by blizzz** [comment]
If my conclusion is correct from the last few comments, saml faces the same issue and uses a dirty hack: https://github.com/nextcloud/user_saml/blob/master/lib/UserBackend.php#L159-L172

But maybe my conclusions are wrong.

Normally this is called in `\OC\User\Session::prepareUserLogin()` which is called during any normal login procedure (user_saml is not normal :scream_cat: ).

**Comment by come-nc** [comment]
So it seems the problem comes from login/lastLogin config user value, which we should most likely not import, so that Nextcloud knows the first login is a first login.
But that means the default files would be copied into the user folder on first login, even if he imported files I think, which we do not want.

**Comment by blizzz** [comment]
That would be analogue to only this line https://github.com/nextcloud/user_saml/blob/master/lib/UserBackend.php#L162
